### ISSUE TITLE
Presets not beeing loaded/saved

### ISSUE THREAD

**Issue by turtlepurple** [Ilias95/FF-Multi-Converter#32] opened 2015-02-07 15:03 UTC
Hey there,
Just installed ffmulticonverter from source on a fresh Debian 7.8 machine (cause there was only .deb's for debian 8 (experimental).
When I open the presets list its empty and when I create a new preset it wont save.

Here's terminal output that appears as soon as I open the presets:

> ffmulticonverter
> Traceback (most recent call last):
>   File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1668, in feed
>     self._parser.Parse(data, 0)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 34,
> column 70
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File
> "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py",
> line 124, in load_xml
>     self.tree = etree.parse(self.current_presets_file)
>   File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1223, in parse
>     tree.parse(source, parser)
>   File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 678, in parse
>     parser.feed(data)
>   File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1670, in feed
>     self._raiseerror(v)
>   File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1543, in
> _raiseerror
>     raise err
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line
> 34, column 70
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File
> "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py",
> line 125, in load_xml
>     except (etree.ParseError, FileNotFoundError):
> NameError: global name 'FileNotFoundError' is not defined
> Traceback (most recent call last):
>   File
> "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py",
> line 153, in fill_presListWidget
>     for i in sorted([y.tag for y in self.root]):
> AttributeError: 'ShowPresets' object has no attribute 'root'

**Comment by Ilias95** [comment] 2015-02-07 21:15
Hello,
I'll need some feedback for this. 

1. Which version of ffmulticonverter did you install?
2. Have you ever installed a previous version?
3. Your python version.
4. The output of:
`ls /usr/share/ffmulticonverter`
`ls /usr/local/share/ffmulticonverter`
`ls ~/.config/ffmulticonverter`
5. Try import the presets list (the ffmulti/share/presets.xml file) and please provide me with any terminal output.

Thanks in advance and thanks for reporting.

**Comment by turtlepurple** [comment] 2015-02-26 23:43
Hey There, back I am - been busy with life :] got the logs from that other Computer now

i DID try to install it with a .deb-package for the wrong (testing - i think its "Jessie") debian-version.
I thought i've purged but im not all sure

Here's a file anyway including python version and everything - hope it helps
I did a find *multiconverter in the end because /usr/share/ff... didnt exist
'FFMulticonverter 1.6.0

Python 3.2.3 - Qt 4.2.8 PyQt 4.9.3 on Linux

~$ ffmulticonverter 
# Open Presets (Menu > Presets)
Traceback (most recent call last):
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1668, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 124, in load_xml
    self.tree = etree.parse(self.current_presets_file)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1223, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 678, in parse
    parser.feed(data)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1670, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1543, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 125, in load_xml
    except (etree.ParseError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 153, in fill_presListWidget
    for i in sorted([y.tag for y in self.root]):
AttributeError: 'ShowPresets' object has no attribute 'root'

# End Open Presets
# Start Add Preset
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 189, in add_preset
    index = sorted([i.tag for i in self.root] + [dialog.name_text])\
AttributeError: 'ShowPresets' object has no attribute 'root'

# End Add Preset

# Import ~/.config/ffmulticonverter/presets.xml

Traceback (most recent call last):
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1668, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 124, in load_xml
    self.tree = etree.parse(self.current_presets_file)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1223, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 678, in parse
    parser.feed(data)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1670, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1543, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 125, in load_xml
    except (etree.ParseError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 153, in fill_presListWidget
    for i in sorted([y.tag for y in self.root]):
AttributeError: 'ShowPresets' object has no attribute 'root'

# End Import


/usr/share/ffmulti dont exist
~$ ls /usr/local/share/ffmulticonverter/
presets.xml
~$ ls ~/.config/ffmulticonverter
FF Muli Converter.conf  logs  presets.xml

~$find /usr -path "*ffmulticonverter*"
/usr/local/bin/ffmulticonverter
/usr/local/share/man/man1/ffmulticonverter.1.gz
/usr/local/share/ffmulticonverter
/usr/local/share/ffmulticonverter/presets.xml
/usr/local/share/applications/ffmulticonverter.desktop
/usr/local/share/pixmaps/ffmulticonverter.png
/usr/local/lib/python3.2/dist-packages/ffmulticonverter
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/utils.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/qrc_resources.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/about_dlg.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/progress.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/utils.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/presets_dlgs.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/preferences_dlg.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/ffmulticonverter.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/__init__.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/qrc_resources.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/about_dlg.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__init__.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/preferences_dlg.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/progress.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/ffmulticonverter.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter-1.6.0.egg-info'

**Comment by turtlepurple** [comment] 2015-02-26 23:48
Hey There, back I am - been busy with life :] got the logs from that other Computer now

i DID try to install it with a .deb-package for the wrong (testing - i think its "Jessie") debian-version.
I thought i've purged but im not all sure

Here's a file anyway including python version and everything - hope it helps
I did a find *multiconverter in the end because /usr/share/ff... didnt exist
'FFMulticonverter 1.6.0

Python 3.2.3 - Qt 4.2.8 PyQt 4.9.3 on Linux
```
~$ ffmulticonverter 
<< Open Presets (Menu > Presets)
Traceback (most recent call last):
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1668, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 124, in load_xml
    self.tree = etree.parse(self.current_presets_file)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1223, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 678, in parse
    parser.feed(data)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1670, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1543, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 125, in load_xml
    except (etree.ParseError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 153, in fill_presListWidget
    for i in sorted([y.tag for y in self.root]):
AttributeError: 'ShowPresets' object has no attribute 'root'

<< End Open Presets
<< Start Add Preset
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 189, in add_preset
    index = sorted([i.tag for i in self.root] + [dialog.name_text])\
AttributeError: 'ShowPresets' object has no attribute 'root'

<< End Add Preset

<< Import ~/.config/ffmulticonverter/presets.xml

Traceback (most recent call last):
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1668, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 124, in load_xml
    self.tree = etree.parse(self.current_presets_file)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1223, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 678, in parse
    parser.feed(data)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1670, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.2/xml/etree/ElementTree.py", line 1543, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 34, column 70

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 125, in load_xml
    except (etree.ParseError, FileNotFoundError):
NameError: global name 'FileNotFoundError' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py", line 153, in fill_presListWidget
    for i in sorted([y.tag for y in self.root]):
AttributeError: 'ShowPresets' object has no attribute 'root'

<< End Import


/usr/share/ffmulti dont exist
~$ ls /usr/local/share/ffmulticonverter/
presets.xml
~$ ls ~/.config/ffmulticonverter
FF Muli Converter.conf  logs  presets.xml

~$find /usr -path "*ffmulticonverter*"
/usr/local/bin/ffmulticonverter
/usr/local/share/man/man1/ffmulticonverter.1.gz
/usr/local/share/ffmulticonverter
/usr/local/share/ffmulticonverter/presets.xml
/usr/local/share/applications/ffmulticonverter.desktop
/usr/local/share/pixmaps/ffmulticonverter.png
/usr/local/lib/python3.2/dist-packages/ffmulticonverter
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/utils.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/qrc_resources.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/presets_dlgs.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/about_dlg.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/progress.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/utils.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/presets_dlgs.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/preferences_dlg.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/ffmulticonverter.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/__init__.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/qrc_resources.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__pycache__/about_dlg.cpython-32.pyc
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/__init__.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/preferences_dlg.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/progress.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter/ffmulticonverter.py
/usr/local/lib/python3.2/dist-packages/ffmulticonverter-1.6.0.egg-info'
```

**Comment by Ilias95** [comment] 2015-02-27 19:57
Hello again,

Unfortunately I can't reproduce this and I don't have access to any debian machine. I tried on a fresh ubuntu installation, but I didn't had any problems with the presets.

I think that it might be a bug with the 1.6.0 version allowing user to insert invalid xml code to the presets file. The bug is now fixed.

It would be very helpful to tell me if you confront any problems with the new - coming very soon - version on that machine.

In order to do it:
1. Remove the program with your package manager (if you finally installed it that way)
2. `git clone https://github.com/Ilias95/FF-Multi-Converter` to get the latest version.
3. Enter the downloaded folder and type `./uninstall.sh --all` (not as root, but you will be asked for root password) to remove all project related files from your system. Make sure that ~/.config/ffmulticonverter is gone. If not, manually delete it.
4. Install the program from source by running `python3 ./launcher install` and check if everything is ok with the presets.

Thank you very much for all your feedback and looking forward to hear if the new version runs properly for you.

**Comment by Ilias95** [comment] 2015-02-28 15:21
I updated the uninstall script.

You should just run `./uninstall.sh` as root and then remove the `~/.config/ffmulticonverter` directory manually.

**Comment by Ilias95** [comment] 2015-04-18 14:54
Fixed: https://github.com/Ilias95/FF-Multi-Converter/commit/62ee45552f81fe64558f40b579457cc93530c7e4

It was finally a small incompatibility with python version 3.2 that Debian stable uses.
Unfortunately it's not included in the latest stable, but you can use the upstream version by cloning this repo.

**Closed by Ilias95** 2015-04-18 14:54 UTC
Labels: bug, presets
